services:
  web:
    restart: always
    build:
      context: ./triki_traka_backend
      dockerfile: Dockerfile.prod
    command: gunicorn triki_traka_backend.wsgi:application --bind 0.0.0.0:8000
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    #ports:
    #  - "8000:8000"  
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db_prod
    
  db_prod:
    restart: always
    image: postgres:12.0-alpine
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - '5432:5432'  
    volumes:
      - ./postgres_data_prod:/var/lib/postgres/data  
    env_file:
      - ./.env.prod.db

  nginx:
    restart: always
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - web

volumes:
  postgres_data_prod:

